car-rent-client/src/main/java/com/ertelecom/carrentclient/dto/CarRentHistoryDto.java
package com.ertelecom.carrentclient.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.time.LocalDate;

@Data
public class CarRentHistoryDto {
	private Long id;
	private Long carRentId;
	private Long pointFromId;
	private Long pointFinishId;
	private Long renterId;

	private String rentFrom;
	private String rentFinish;
}

car-rent-client/src/main/java/com/ertelecom/carrentclient/model/Car.java
package com.ertelecom.carrentclient.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Car {
	private Long id;
	private String name;
	private String number;
}

car-rent-client/src/main/java/com/ertelecom/carrentclient/model/CarRentHistory.java
package com.ertelecom.carrentclient.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class CarRentHistory {
	private Long id;
	private Car car;
	private Point pointFrom;
	private Point pointFinish;
	private Renter renter;
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
	private LocalDate rentFrom;
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
	private LocalDate rentFinish;
	private CarTimeCounter counter;
}

car-rent-client/src/main/java/com/ertelecom/carrentclient/model/CarTimeCounter.java
package com.ertelecom.carrentclient.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class CarTimeCounter {
	private Car car;

	private Point point;

	private Long counter;
	private Long days;

	public Double getAverage() {
		return (double) days / counter;
	}
}

car-rent-client/src/main/java/com/ertelecom/carrentclient/model/Point.java
package com.ertelecom.carrentclient.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Point {
	private Long id;
	private String city;
	private String address;
}

car-rent-client/src/main/java/com/ertelecom/carrentclient/model/Renter.java
package com.ertelecom.carrentclient.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Renter {
	private Long id;
	private String name;
}

car-rent-client/src/main/java/com/ertelecom/carrentclient/controller/IndexController.java
package com.ertelecom.carrentclient.controller;

import com.ertelecom.carrentclient.dto.CarRentHistoryDto;
import com.ertelecom.carrentclient.helper.RestPage;
import com.ertelecom.carrentclient.model.Car;
import com.ertelecom.carrentclient.model.CarRentHistory;
import com.ertelecom.carrentclient.model.Point;
import com.ertelecom.carrentclient.model.Renter;
import com.ertelecom.carrentclient.util.JacksonUtil;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.netflix.appinfo.InstanceInfo;
import com.netflix.discovery.EurekaClient;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.client.RestTemplate;

import java.util.List;

@Controller
public class IndexController {

	private final String urlRest;

	public IndexController(EurekaClient eurekaClient) {

		InstanceInfo service = eurekaClient
				.getApplication("Car Rent")
				.getInstances()
				.get(0);

		String hostName = service.getHostName();
		int port = service.getPort();

		this.urlRest = "http://" + hostName + ":" + port;
	}

	@GetMapping({"/"})
	public String index(Model model,
						@RequestParam(defaultValue = "0") long carId,
						@RequestParam(defaultValue = "0") int page,
						@RequestParam(defaultValue = "10") int size) throws JsonProcessingException {

		RestTemplate restTemplate = new RestTemplate();
		String response = restTemplate.getForEntity(this.urlRest + "/api/history/getPages?page=" + page + "&size=" + size + "&carId=" + carId, String.class).getBody();
		RestPage<CarRentHistory> history = JacksonUtil.getMapper().readValue(response, new TypeReference<>() {
		});
		model.addAttribute("page", history);
		model.addAttribute("url", "/?carId=" + carId);

		return "index";
	}

	@GetMapping("/addHistory")
	public String addHistory(@RequestParam(defaultValue = "0") long historyId,
							 Model model) throws JsonProcessingException {

		RestTemplate restTemplate = new RestTemplate();
		String response = restTemplate.getForEntity(this.urlRest + "/api/cars/getAll", String.class).getBody();
		List<Car> cars = JacksonUtil.getMapper().readValue(response, new TypeReference<>() {
		});

		model.addAttribute("cars", cars);

		response = restTemplate.getForEntity(this.urlRest + "/api/points/getAll", String.class).getBody();
		List<Point> points = JacksonUtil.getMapper().readValue(response, new TypeReference<>() {
		});

		model.addAttribute("points", points);

		response = restTemplate.getForEntity(this.urlRest + "/api/renters/getAll", String.class).getBody();
		List<Renter> renters = JacksonUtil.getMapper().readValue(response, new TypeReference<>() {
		});

		model.addAttribute("renters", renters);

		if(historyId != 0) {
			response = restTemplate.getForEntity(this.urlRest + "/api/history/get/" + historyId, String.class).getBody();
			List<Renter> history = JacksonUtil.getMapper().readValue(response, new TypeReference<>() {
			});

			model.addAttribute("history", history);
		} else {
			model.addAttribute("history", null);
		}


		return "addHistory";
	}

	@PostMapping("/addHistory")
	public String addHistory(CarRentHistoryDto carRentHistory) {
		RestTemplate restTemplate = new RestTemplate();

		HttpEntity<CarRentHistoryDto> request = new HttpEntity<>(carRentHistory);
		restTemplate.postForObject(this.urlRest + "/api/history/create", request, CarRentHistoryDto.class);

		return "redirect:/";
	}
}

car-rent-client/src/main/java/com/ertelecom/carrentclient/controller/ServiceInstanceRestController.java
package com.ertelecom.carrentclient.controller;

import org.springframework.cloud.client.ServiceInstance;
import org.springframework.cloud.client.discovery.DiscoveryClient;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController
class ServiceInstanceRestController {

	private final DiscoveryClient discoveryClient;

	ServiceInstanceRestController(DiscoveryClient discoveryClient) {
		this.discoveryClient = discoveryClient;
	}

	@RequestMapping("/service-instances/{applicationName}")
	public List<ServiceInstance> serviceInstancesByApplicationName(
			@PathVariable String applicationName) {
		return this.discoveryClient.getInstances(applicationName);
	}
}

car-rent-client/src/main/resources/templates/addHistory.ftl
<#import "./layout/defaultLayout.ftl" as layout>
<@layout.newLayout>
<form class="form-signin" method="post" action="/addHistory">
	<h2 class="form-signin-heading">Add to history</h2>
	<p>
		<label for="carId" class="sr-only">Car</label>
		<select name="carRentId" class="form-select" aria-label="">
			<#list cars as car>
				<option value="${car.id}" selected>${car.name} ${car.number}</option>
            </#list>
		</select>
	</p>
	<p>
		<label for="pointFromId" class="sr-only">Point from</label>
		<select name="pointFromId" class="form-select" aria-label="">
            <#list points as point>
				<option value="${point.id}" selected>${point.city}, ${point.address}</option>
            </#list>
		</select>
	</p>
	<p>
		<label for="pointFinishId" class="sr-only">Point finish</label>
		<select name="pointFinishId" class="form-select" aria-label="">
            <#list points as point>
				<option value="${point.id}" selected>${point.city}, ${point.address}</option>
            </#list>
		</select>
	</p>
	<p>
		<label for="renterId" class="sr-only">Renter finish</label>
		<select name="renterId" class="form-select" aria-label="">
            <#list renters as renter>
				<option value="${renter.id}" selected>${renter.name}</option>
            </#list>
		</select>
	</p>

	<p>
	<label for="rentFrom" class="sr-only">Start time of rent</label>
	<input class="form-select" name="rentFrom" data-provide="datepicker" data-date-format="yyyy-mm-dd">
	</p>

	<p>
	<label for="rentFinish" class="sr-only">Start time of rent</label>
	<input class="form-select" name="rentFinish" data-provide="datepicker" data-date-format="yyyy-mm-dd">
	</p>

	<button class="btn btn-lg btn-primary btn-block" type="submit"><#if !history??>Create<#else>Edit</#if></button>
</form>
	<script type="text/javascript">
        $('.datepicker').datepicker({
            format: 'yyyy-mm-dd'
        });
	</script>
</@layout.newLayout>

car-rent-client/src/main/resources/templates/index.ftl
<#import "./layout/defaultLayout.ftl" as layout>
<@layout.newLayout>
	<a href="/addHistory" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Create history</a>
	<table class="table">
		<tr>
			<th>Car model</th>
			<th>Point from</th>
			<th>Average days at point</th>
			<th>Point finish</th>
			<th>Renter full name</th>
			<th>Start time of rent</th>
			<th>Finish time of rent</th>
		</tr>
        <#list page.content as content>
			<tr>
				<td><a href="/?carId=${content.car.id}">${content.car.name} ${content.car.number}</a></td>
				<td>${content.pointFrom.city}, ${content.pointFrom.address}</td>
				<td>${content.counter.average}</td>
				<td>${content.pointFinish.city}, ${content.pointFinish.address}</td>
				<td>${content.renter.name}</td>
				<td>${content.rentFrom}</td>
				<td>${content.rentFinish}</td>
			</tr>
        </#list>
	</table>
    <#import "./layout/pager.ftl" as p>
    <@p.pager page url />
</@layout.newLayout>

car-rent-client/src/main/resources/templates/layout/defaultLayout.ftl
<#setting number_format="computer">
<#macro newLayout title="">
<!DOCTYPE html>
<html lang="en" ng-app="app">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>Client Car Rent</title>
	<link rel="stylesheet" href="/js/bootstrap/dist/css/bootstrap.css" type="text/css">
	<link rel="stylesheet" href="/js/bootstrap/dist/css/bootstrap-grid.css" type="text/css">
	<link rel="stylesheet" href="js/datepicker/css/bootstrap-datepicker.css" type="text/css">
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="/js/bootstrap/dist/js/bootstrap.min.js"></script>
	<script src="/js/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="/js/datepicker/js/bootstrap-datepicker.min.js"></script>
</head>
<body>
<div class="container-fluid">
    <#nested/>
</div>
</body>
</html>
</#macro>

car-rent-client/src/main/resources/templates/layout/pager.ftl
<#macro pager page url="" >
    <#if page.getTotalPages() gt 7>
        <#assign
            totalPages = page.getTotalPages()
            pageNumber = page.getNumber() + 1

            head = (pageNumber > 4)?then([1, -1], [1, 2, 3])
            tail = (pageNumber < totalPages - 3)?then([-1, totalPages], [totalPages - 2, totalPages - 1, totalPages])
            bodyBefore = (pageNumber > 4 && pageNumber < totalPages - 1)?then([pageNumber - 2, pageNumber - 1], [])
            bodyAfter = (pageNumber > 2 && pageNumber < totalPages - 3)?then([pageNumber + 1, pageNumber + 2], [])

            body = head + bodyBefore + (pageNumber > 3 && pageNumber < totalPages - 2)?then([pageNumber], []) + bodyAfter + tail
        >
    <#else>
        <#assign body = 1..page.getTotalPages()>
    </#if>
    <div class="container mt-3">
        <div class="row">
            <ul class="pagination col justify-content-center">
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Pages</a>
                </li>
            <#list body as p>
                <#if (p - 1) == page.getNumber()>
                    <li class="page-item active">
                        <a class="page-link" href="#" tabindex="-1">${p}</a>
                    </li>
                <#elseif p == -1>
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">...</a>
                    </li>
                <#else>
                    <li class="page-item">
                        <a class="page-link" href="${url}&page=${p - 1}&size=${page.getSize()}" tabindex="-1">${p}</a>
                    </li>
                </#if>
            </#list>
            </ul>

            <ul class="pagination col justify-content-center">
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Elements on page</a>
                </li>
            <#list [5, 10, 25, 50] as c>
                <#if c == page.getSize()>
                    <li class="page-item active">
                        <a class="page-link" href="#" tabindex="-1">${c}</a>
                    </li>
                <#else>
                    <li class="page-item">
                        <a class="page-link" href="${url}&page=${page.getNumber()}&size=${c}" tabindex="-1">${c}</a>
                    </li>
                </#if>
            </#list>
            </ul>
        </div>
    </div>
</#macro>